### ISSUE TITLE
Type of a function

### ISSUE THREAD

**Issue by gbracha** [lrhn/dep-optionals#4]
Section 9.3 is unchanged in the draft.  It should describe the type of a function that has both optional positionals and named arguments.

**Comment by gbracha** [comment]
This then spills over into 16.10 which needs to describe the types of function literals that might take both kinds of optional parameters.

**Comment by lrhn** [comment]
Both sections have now been updated as well. For 16.10, the combination of positional and named optionals into one case makes the section shorter. The 9.3 section seems to be more elaborate, and handles the case with no optional parameters explicitly, so I added an extra case to that instead of combining positional and named.

**Comment by lrhn** [comment]
But I still need to fix the Function Types section (19.5).

**Comment by lrhn** [comment]
Now also updated.
